export enum AuctionFilter {
  BUY_NOW_PRICE_FROM = 'BUY_NOW_PRICE_FROM',
  BUY_NOW_PRICE_TO = 'BUY_NOW_PRICE_TO',
  BID_PRICE_FROM = 'BID_PRICE_FROM',
  BID_PRICE_TO = 'BID_PRICE_TO',
  ONLY_PROMOTED = 'ONLY_PROMOTED',
  ONLY_BUY_NOW = 'ONLY_BUY_NOW',
  ONLY_CAN_BID = 'ONLY_CAN_BID'
}
